=== lvsravikanth/freequent/trunk/resource/tableinstaller/sql-schema-2-4.dtd
<!ELEMENT schema (source-config?, comment?, storage-directive*, tablegroup*) >
<!ELEMENT storage-directive (property-set+)>
<!ELEMENT property-set (property+)>
<!ELEMENT property EMPTY>
<!ELEMENT tablegroup (comment*, (table|rowset)+)>
<!ELEMENT table (comment?, column*, index*, key-ref*) >
<!ELEMENT column (comment?) >
<!ELEMENT index (comment?) >
<!ELEMENT key-ref (comment?) >
<!ELEMENT rowset (row+) >
<!ELEMENT row (item*) >
<!ELEMENT item EMPTY >
<!ELEMENT comment (#PCDATA) >

<!ATTLIST schema
   portable (true|false) #IMPLIED
   version CDATA #REQUIRED
   version-table CDATA #IMPLIED
   archive-dir CDATA #IMPLIED
   conversions-file CDATA #IMPLIED
>

<!ATTLIST storage-directive
   name CDATA #REQUIRED
   comment CDATA #IMPLIED
>

<!ATTLIST property-set
   database CDATA #IMPLIED
   comment CDATA #IMPLIED
>

<!ATTLIST property
   name CDATA #REQUIRED
   value CDATA #REQUIRED
   comment CDATA #IMPLIED
>

<!ATTLIST tablegroup
   name CDATA #REQUIRED
   comment CDATA #IMPLIED
>

<!ATTLIST table
   name CDATA #REQUIRED
   storage CDATA #IMPLIED
   comment CDATA #IMPLIED
>

<!ATTLIST column
   name CDATA #REQUIRED
   type CDATA #REQUIRED
   size CDATA #IMPLIED
   no-nulls (true|false) "false"
   default CDATA #IMPLIED
   autoincrement (true|false) "false"
   decimal-places CDATA #IMPLIED
   multibyte (true|false) "false"
   collation CDATA #IMPLIED
>

<!ATTLIST index
   name CDATA #IMPLIED
   unique (true|false) #IMPLIED
   primary-key (true|false) "false"
   clustered (true|false) "false"
   columns CDATA #REQUIRED
>

<!ATTLIST key-ref
   name CDATA #IMPLIED
   columns CDATA #REQUIRED
   table CDATA #REQUIRED
   references CDATA #REQUIRED
   rule (restricted|cascade) "restricted"
>

<!ATTLIST rowset
   table CDATA #REQUIRED
   create (true|false) "true"
   upgrade (true|false) "true"
>

<!ATTLIST row
   create (true|false) "true"
   upgrade (true|false) "true"
>

<!ATTLIST item
   column CDATA #REQUIRED
   value CDATA #REQUIRED
>

=== lvsravikanth/freequent/trunk/resource/tableinstaller/tables.xml
<?xml version="1.0" encoding="windows-1252"?>
<!DOCTYPE schema PUBLIC "http://www.epicentric.com/dtd/sql-schema-2-4.dtd" "./sql-schema-2-4.dtd">
<schema version-table="Freequent_Version" version="1.0">
	<tablegroup name="FreequentTables">
		<table name="Freequent_Version" >
			  <comment>
			   This table stores the Freequent Application Builder version ID and
			   last update time stamp.
			  </comment>
			  <column name="version_id" type="varchar" size="20" no-nulls="true" />
			  <column name="last_update" type="timestamp" />
			  <index name="PK_Freequent_Version" columns="version_id" primary-key="true"/>
		 </table>

		<table name="TestTable">
			<column name="ID" no-nulls="true" size="40" type="integer"  autoincrement="false"/>
			<column name="USERNAME" no-nulls="true" size="100" type="varchar" />
			<column name="PASSWORD" no-nulls="true" size="100" type="varchar" />
			<index name="UNIQUEID_PK" columns="ID" primary-key="true" />
		</table>

		<rowset table="TestTable">
			<row>
				<item column="ID" value="1"/>
				<item column="USERNAME" value="admin"/>
				<item column="PASSWORD" value="admin"/>
			</row>
		</rowset>

	</tablegroup>

</schema>

=== lvsravikanth/freequent/resource/tableinstaller/tables.xml
<?xml version="1.0" encoding="windows-1252"?>
<!DOCTYPE schema PUBLIC "http://www.epicentric.com/dtd/sql-schema-2-4.dtd" "./sql-schema-2-4.dtd">
<schema version-table="Freequent_Version" version="1.0">
	<tablegroup name="FreequentTables">
		<table name="Freequent_Version" >
			  <comment>
			   This table stores the Freequent Application Builder version ID and
			   last update time stamp.
			  </comment>
			  <column name="version_id" type="varchar" size="20" no-nulls="true" />
			  <column name="last_update" type="timestamp" />
			  <index name="PK_Freequent_Version" columns="version_id" primary-key="true"/>
		 </table>

        <table name="FTUSERS">
			<column name="USER_ID" no-nulls="true" size="40" type="varchar"  autoincrement="false"/>
			<column name="FIRST_NAME" no-nulls="true" size="80" type="varchar" />
			<column name="MIDDLE_NAME" no-nulls="false" size="80" type="varchar" />
			<column name="LAST_NAME" no-nulls="false" size="80" type="varchar" />
			<column name="PASSWORD" no-nulls="true" size="80" type="varchar" />
			<column name="DISABLED"  no-nulls="true" default="false"  type="bit"/>
			<column name="EXPIRESON"  no-nulls="false" type="timestamp"/>
			<column name="CREATEDBY" no-nulls="true" size="40" type="varchar"/>
			<column name="CREATEDON" no-nulls="true" type="timestamp"/>
			<column name="MODIFIEDBY" no-nulls="true" size="40" type="varchar"/>
			<column name="MODIFIEDON" no-nulls="true" type="timestamp"/>
			<index name="USER_ID_PK" columns="USER_ID" primary-key="true" />
		</table>

        <table name="ftCapabilityInfo">
            <column name="name" type="varchar" size="80" no-nulls="true"/>
            <column name="supportsRead" type="bit" default="true" no-nulls="true"/>
            <column name="supportsWrite" type="bit" default="false" no-nulls="true"/>
            <column name="supportsDelete" type="bit" default="false" no-nulls="true"/>
            <index name="PK_ftCapabilityInfo_name" columns="name" primary-key="true"/>
        </table>

        <table name="ftUserCapabilityInfo">
            <column name="capabilityName" type="varchar" size="80" no-nulls="true"/>
            <column name="hasRead" type="bit" default="false" no-nulls="true"/>
            <column name="hasWrite" type="bit" default="false" no-nulls="true"/>
            <column name="hasDelete" type="bit" default="false" no-nulls="true"/>
            <column name="userId" type="varchar" size="40" no-nulls="true"/>
            <index name="IDX_ftUserCapabilityInfo_capName_userId" columns="capabilityName,userId" unique="true"/>
            <key-ref name="FK_ftUserCapabilityInfo_capabilityName" columns="capabilityName" table="ftCapabilityInfo"
                     references="name" rule="cascade"/>
            <key-ref name="FK_ftUserCapabilityInfo_userId" columns="userId" table="FTUSERS" references="USER_ID"
                     rule="cascade"/>
        </table>

		<table name="ftItem">
			<column name="id" no-nulls="true" size="40" type="varchar"/>
			<column name="name" no-nulls="true" size="80" type="varchar" />
			<column name="code" no-nulls="true" size="40" type="varchar" />
			<column name="groupName" no-nulls="false" size="20" type="varchar" />
			<column name="price" no-nulls="true" size="10" type="decimal"  decimal-places="3"/>
			<column name="priceQty" no-nulls="false" type="integer"/>  <!-- the price is for how much qty? -->
			<column name="unit" no-nulls="true" type="varchar" size="20"/>
			<column name="category" no-nulls="false" type="varchar" size="80"/>
			<index name="PK_ftItem_id" columns="id" primary-key="true" />
			<index name="IDX_ftItem_name" columns="name" unique="true"/>
			<index name="IDX_ftItem_code" columns="code" unique="true"/>
			<key-ref name="FK_ftItem_groupName" columns="groupName" table="ftGroup"
                     references="name" rule="cascade"/>
			<key-ref name="FK_ftItem_unit" columns="unit" table="ftUnit"
                     references="name" rule="cascade"/>
			<key-ref name="FK_ftItem_category" columns="category" table="ftCategory"
                     references="name" rule="cascade"/>
		</table>

		<table name="ftUnit">
			<column name="id" no-nulls="true" size="40" type="varchar"/>
			<column name="name" no-nulls="true" size="20" type="varchar"/>
			<column name="description" no-nulls="false" size="1024" type="varchar"/>
			<index name="PK_ftUnit_id" columns="id" primary-key="true" />
			<index name="IDX_ftUnit_name" columns="name" unique="true"/>
		</table>

		<table name="ftGroup">
			<column name="id" no-nulls="true" size="40" type="varchar"/>
			<column name="name" no-nulls="true" size="20" type="varchar"/>
			<column name="description" no-nulls="false" size="1024" type="varchar"/>
			<index name="PK_ftGroup_id" columns="id" primary-key="true" />
			<index name="IDX_ftGroup_name" columns="name" unique="true"/>
		</table>

		<table name="ftCategory">
			<column name="id" no-nulls="true" size="40" type="varchar"/>
			<column name="name" no-nulls="true" size="80" type="varchar"/>
			<column name="description" no-nulls="false" size="1024" type="varchar"/>
			<index name="PK_ftCategory_id" columns="id" primary-key="true" />
			<index name="IDX_ftCategory_name" columns="name" unique="true"/>
		</table>

		<table name="ftCategoryAssoc">
			<column name="objId" no-nulls="true" size="40" type="varchar"/>
			<column name="categoryId" no-nulls="true" size="40" type="varchar"/>
			<index name="IDX_ftCategoryAssoc_objId_catId" columns="objId, categoryId" unique="true"/>
		</table>

		<table name="ftRecord">
			<column name="recordId" no-nulls="true" size="40" type="varchar"/>
			<column name="objectId" no-nulls="true" size="40" type="varchar"/>
			<column name="objectType" no-nulls="true" size="40" type="varchar"/>
			<column name="createdBy" no-nulls="true" size="40" type="varchar"/>
			<column name="createdOn" no-nulls="true" type="timestamp"/>
			<column name="modifiedBy" no-nulls="true" size="40" type="varchar"/>
			<column name="modifiedOn" no-nulls="true" type="timestamp"/>
			<index name="PK_ftRecord_recordId" columns="recordId" primary-key="true" />
			<index name="IDX_ftRecord_objectId" columns="objectId" unique="true"/>
		</table>

        <!-- master data -->
        <rowset table="FTUSERS">
			<row>
				<item column="USER_ID" value="admin"/>
				<item column="FIRST_NAME" value="admin"/>
				<item column="LAST_NAME" value="admin"/>
				<item column="PASSWORD" value="55,107,-47,13,47,97,113,-69,-3,10,-78,-88,19,-25,-80,29,"/>
				<item column="EXPIRESON" value="2019-10-16 00.00.00" />
				<item column="CREATEDBY" value="admin" />
				<item column="CREATEDON" value="2013-10-16 00.00.00" />
				<item column="MODIFIEDBY" value="admin" />
				<item column="MODIFIEDON" value="2013-10-16 00.00.00" />
			</row>
		</rowset>

		<rowset table="ftCapabilityInfo">
			<row>
				<item column="name" value="USER"/>
				<item column="supportsRead" value="true"/>
				<item column="supportsWrite" value="true"/>
				<item column="supportsDelete" value="true"/>
			</row>
			<row>
				<item column="name" value="MANAGE_ITEMS"/>
				<item column="supportsRead" value="true"/>
				<item column="supportsWrite" value="true"/>
				<item column="supportsDelete" value="true"/>
			</row>
		</rowset>

		<rowset table="ftUnit">
			<row>
				<item column="id" value="U-pcs-000000000000000000000000000000UNIT"/>
				<item column="name" value="pcs"/>
			</row>
		</rowset>

		<rowset table="ftGroup">
			<row>
				<item column="id" value="G-soups-0000000000000000000000000000GRUP"/>
				<item column="name" value="SOUPS"/>
			</row>
			<row>
				<item column="id" value="G-raita-0000000000000000000000000000GRUP"/>
				<item column="name" value="RAITA"/>
			</row>
			<row>
				<item column="id" value="G-rice-00000000000000000000000000000GRUP"/>
				<item column="name" value="RICE"/>
			</row>
			<row>
				<item column="id" value="G-muttonmusti-0000000000000000000000GRUP"/>
				<item column="name" value="MUTTON MUSTI"/>
			</row>
			<row>
				<item column="id" value="G-biryani-00000000000000000000000000GRUP"/>
				<item column="name" value="BIRYANI"/>
			</row>
		</rowset>
		<rowset table="ftCategory">
			<row>
				<item column="id" value="C-veg-000000000000000000000000000000CTGR"/>
				<item column="name" value="veg"/>
			</row>
			<row>
				<item column="id" value="C-non-veg-00000000000000000000000000CTGR"/>
				<item column="name" value="non-veg"/>
			</row>
		</rowset>
	</tablegroup>

</schema>
