=== lvsravikanth/freequent/trunk/src/com/scalar/core/menu/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.samskritiInfo.com"
    xmlns="http://www.samskritiInfo.com"
    elementFormDefault="qualified">

    <xsd:element name="menus" type="menusType"/>
    <xsd:complexType name="menusType">
        <xsd:sequence>
            <xsd:element name="menu" type="menuType" maxOccurs="10"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="menuType">
        <xsd:sequence>
            <xsd:element name="link" type="xsd:string"/>
            <xsd:element name="enabled" type="xsd:boolean"/>
            <xsd:element name="display" type="xsd:boolean"/>
            <xsd:element name="capability" type="capabilityType"/>
            <xsd:element name="menuItems" type="menuItemsType" maxOccurs="1" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="menuItemsType">
        <xsd:complexContent>
            <xsd:extension base="menusType"/>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:complexType name="capabilityType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="type" use="required">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="read"/>
                        <xsd:enumeration value="write"/>
                        <xsd:enumeration value="delete"/>
                    </xsd:restriction>
                </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

</xsd:schema>

=== lvsravikanth/freequent/trunk/src/com/scalar/core/menu/menu.xml
<?xml version="1.0" encoding="UTF-8"?>

<menus xmlns="http://www.samskritiInfo.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.samskritiInfo.com menu.xsd">
    <menu name="Admin" id="1">
        <link/>
        <enabled>true</enabled>
        <display>true</display>
        <capability type="read"><name></name></capability>
        <menuItems>
            <menu name="Manage Users" id="1.1">
                <link>manageusers</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>USER</name></capability>
            </menu>
            <menu name="Manage Groups" id="1.2">
                <link>managegroups</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>GROUP</name></capability>
            </menu>
            <menu name="Manage Categories" id="1.2">
                <link>managecategories</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>CATEGORY</name></capability>
            </menu>
            <menu name="Manage Units" id="1.2">
                <link>manageunits</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>UNIT</name></capability>
            </menu>
			<menu name="Manage Items" id="1.2">
                <link>manageitems</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>ITEM</name></capability>
            </menu>
        </menuItems>
    </menu>
	<menu name="Sales" id="sales">
		<link/>
		<enabled>true</enabled>
		<display>true</display>
		<capability type="read"><name>SALES</name></capability>
		<menuItems>
			<menu name="Manage Orders" id="manageorders">
				<link>manageorders</link>
				<enabled>true</enabled>
				<display>true</display>
				<capability type="read"><name>ORDER</name></capability>
			</menu>
			<menu name="Manage Invoices" id="manageinvoices">
				<link>manageinvoices</link>
				<enabled>true</enabled>
				<display>true</display>
				<capability type="read"><name>INVOICE</name></capability>
			</menu>
		</menuItems>
	</menu>
    <menu name="Demo" id="demo">
        <link>demo</link>
        <enabled>true</enabled>
        <display>true</display>
        <capability type="read"><name></name></capability>
    </menu>
</menus>

=== lvsravikanth/freequent/src/com/scalar/core/menu/menu.xml
<?xml version="1.0" encoding="UTF-8"?>

<menus xmlns="http://www.samskritiInfo.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.samskritiInfo.com menu.xsd">
    <menu name="Admin" id="1">
        <link>jsp/admin/admin.view</link>
        <enabled>true</enabled>
        <display>true</display>
        <capability type="read"><name>Admin Page</name></capability>
        <menuItems>
            <menu name="User Setup" id="1.1">
                <link>userSetup.htm</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>User Setup</name></capability>
            </menu>
            <menu name="Login Details" id="1.2">
                <link>userSetup.htm</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>User Setup</name></capability>
            </menu>
            <menu name="Accounts Setup" id="1.3">
                <link>accountsSetupSearch.htm</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>Accounts Setup</name></capability>
            </menu>
            <menu name="Reports" id="1.4">
                <link>adminReports.htm</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>User Setup</name></capability>
                <menuItems>
                    <menu name="User Report" id="1.4.1">
                        <link>userReport.htm</link>
                        <enabled>true</enabled>
                        <display>true</display>
                        <capability type="read"><name>User Report</name></capability>
                    </menu>
                    <menu name="User Login Report" id="1.4.2">
                        <link>userLoginReport.htm</link>
                        <enabled>true</enabled>
                        <display>true</display>
                        <capability type="read"><name>User Login Report</name></capability>
                    </menu>
                </menuItems>
            </menu>
        </menuItems>
    </menu>
    <menu name="Operations" id="2">
        <link>jsp/operations/operations.read</link>
        <enabled>true</enabled>
        <display>true</display>
        <capability type="read"><name></name></capability>
        <menuItems>
            <menu name="Inventory Data Entry" id="2.1">
                <link>invDataEntry.htm</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>Inventory Data Entry</name></capability>
            </menu>
            <menu name="Product Report" id="2.2">
                <link>userSetup.htm</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>User Setup</name></capability>
            </menu>
        </menuItems>
    </menu>
    <menu name="Finance" id="3">
        <link>jsp/finance/finance.read</link>
        <enabled>true</enabled>
        <display>true</display>
        <capability type="read"><name></name></capability>
        <menuItems>
            <menu name="Cash Receipts" id="3.1">
                <link>cashTransactionSearch.htm?mode=receipts</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>Cash Receipts Entry</name></capability>
            </menu>
            <menu name="Cash Payments" id="3.2">
                <link>cashTransactionSearch.htm?mode=payments</link>
                <enabled>true</enabled>
                <display>true</display>
                <capability type="read"><name>Cash Payments Entry</name></capability>
            </menu>
        </menuItems>
    </menu>
    <menu name="Demo" id="demo">
        <link>demo</link>
        <enabled>true</enabled>
        <display>true</display>
        <capability type="read"><name></name></capability>
    </menu>
</menus>
